# core/prompting.py
"""
Defines systems prompts, input sanitization, and message building for the AI Copilot agent.
"""

#Dependecies
import unicodedata
import re 


SYSTEM_PROMPTS = {
    "SP_DEFAULT": """
Eres AI Copilot, un asistente conversacional breve, claro y seguro.
Tus funciones principales son:
1) Tareas diarias: creación de notas, recordatorios y gestión ligera de agenda.
2) Búsqueda rápida de información verificable.
3) Educación y productividad: explicaciones claras, guías paso a paso y apoyo contextual.

Instrucciones globales:
- Mantén siempre respuestas breves y puntuales.
- Si la solicitud no corresponde a tus funciones, explica tus límites y ofrece alternativas útiles.
- Si el usuario agradece, confirma y continúa normalmente (no cierres la sesión).
- Si detectas intención peligrosa o inapropiada, recházala con cortesía.
- Siempre responde en español.
""",

     "SP_NOTE": """
Eres AI Copilot. Tu función actual es registrar una nota.
- El contenido ya incluye la fecha generada automáticamente por el sistema.
- No solicites la fecha al usuario ni intentes interpretarla.
- Extrae el contenido principal y genera una respuesta breve confirmando la nota.
- No inventes información adicional.
"""
,
    "SP_REMINDER": """
Eres AI Copilot. Tu función actual es crear un recordatorio.

Instrucciones:
- Identifica claramente qué se debe recordar.
- Si falta la fecha, pídesela al usuario explícitamente.
- Solo acepta fechas en los formatos:
      • '5 de diciembre'
      • '05/12/2025'
- Si la fecha es inválida o pasada, explica el error y solicita una fecha válida.
- Si ya existe fecha válida, confirma el recordatorio en una sola respuesta, sin extender la conversación.
- Mantén el estilo breve, claro y directo.
""",


    "SP_SEARCH": """
Eres AI Copilot actuando como buscador rápido.
- Responde únicamente con datos verificables.
- Si la información no es reciente o no estás seguro, dilo explícitamente.
- Resume la información en 3–5 líneas.
- Evita conversación adicional; responde directo al objetivo de la búsqueda.
""",

    "SP_AGENDA": """
Eres AI Copilot. Tu función es interpretar, organizar y presentar elementos de agenda.
- Usa formato ordenado y conciso.
- No inventes eventos no mencionados.
""",

"SP_VIEWNOTE": """
Eres AI Copilot. Tu tarea es ayudar al usuario a visualizar una nota previamente registrada.
- Si no especifica cuál nota, pídeselo.
- Si la nota no existe en el contexto, indícalo.
- No inventes contenido.
""",


    "SP_LIMIT": """
Has alcanzado el límite de turnos por sesión.
Indica amablemente que se ha reiniciado la conversación.
"""
}



"""
Sanitize and validate user input to ensure safety and appropriateness."""
def sanitize_input(text: str) -> str:
    if not text: 
        return "Entrada vacía. Por favor proporciona más detalles."
    
    #1. Unicode normalization 
    text= unicodedata.normalize("NFKC", text)
    
    #2. Remove control characters
    text = re.sub(r'[\x00-\x1F\x7F]', "", text)

    #3.  Simple emoji or corrupt emoji removal
    emoji= re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F780-\U0001F7FF"  # geometric shapes extended
        "\U0001F800-\U0001F8FF"  # supplemental arrows
        "\U0001F900-\U0001F9FF"  # supplemental symbols/pictographs
        "\U0001FA00-\U0001FA6F"  # chess symbols, etc
        "\U0001FA70-\U0001FAFF"
        "\U00002702-\U000027B0"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE,
    )
    text= emoji.sub(r"", text)

    #4. Collapse whitespace
    text= " ".join(text.split())

    #5. Truncate to 2000 characters
    if len(text)>2000:
        text= text[:2000]
    
    #6. Dangerous content check (simple keyword filter)
    dangerous_keywords= [
        "hackear", "explosivo", "droga", "armas", "terrorismo", "suicid",
        "violencia", "ddos", "malware", "pornografía", "matarme", "amenaza"
        ]
    lowered= text.lower()
    for keyword in dangerous_keywords:
        if keyword in lowered:
            return "Lo siento, no puedo ayudar con esa solicitud."  
    return text.strip()


"""
Build the final message list for the LLM model: 
System message based on the detected intent
Recent history generated by ConversationManager
 New user message
"""
def build_messages(prompt_key: str, history:list, user_input:str ):
    prompt = SYSTEM_PROMPTS.get(prompt_key, SYSTEM_PROMPTS["SP_DEFAULT"])
    
    messages= [{"role": "system", "content": prompt}]

    #Append conversation history (already truncated)
    for turn in history:
        messages.append({"role": turn["role"], "content": turn["content"]})

    # Current turn
    messages.append({"role": "user", "content": user_input})

    return messages
